force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <label>Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/Number_of_cars__c.field-meta.xml
<CustomField>
    <fullName>Number_of_cars__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of cars</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SellerUpdageMnpl.cls
public with sharing class SellerUpdageMnpl {
    public static void incrementNumberOfCars(List<Seller__c> sellers) {
        for(Seller__c seller : sellers) {
            seller.Number_of_cars__c += 1;
        }
        update sellers;
    }

    public static void decrementNumberOfCars(List<Seller__c> sellers) {
        for(Seller__c seller : sellers) {
            if(seller.Number_of_cars__c > 0) {
                seller.Number_of_cars__c -= 1;
            }
        }
        update sellers;
    }
}