force-app/main/default/objects/Model__c/Model__c.object-meta.xml
<CustomObject>
    <label>Model</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Model__c/fields/Eco_friendly__c.field-meta.xml
<CustomField>
    <fullName>Eco_friendly__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Eco friendly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Model__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ModelsUtils.cls
public with sharing class ModelsUtils {
    // Show models
    @AuraEnabled
    public static List<Model__c> showModels() {
        return [SELECT Name, Price__c FROM Model__c WITH SECURITY_ENFORCED];
    }

    // Add model
    @AuraEnabled
    public static String addModel(String name, Boolean ecoFriendly, Integer price) {
        try {
            Integer getModelsWithTheSameName = [SELECT COUNT() FROM Model__c WHERE Name = :name];
            
            if(getModelsWithTheSameName == 0) {
                Model__c model = new Model__c(
                    Name=name,
                    Eco_friendly__c=ecoFriendly,
                    Price__c=price
                );
                insert model;

                return 'ADDED-MODEL';
            } else {
                return 'MODEL-EXISTS';
            }
        } catch(Exception e) {
            System.debug(e.getMessage());
            return 'ERROR-OCCURED';
        }
    }
}