force-app/main/default/objects/Archive_Sale__c/Archive_Sale__c.object-meta.xml
<CustomObject>
    <label>Archive Sale</label>
    <nameField>
        <label>Archive Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archive Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archive_Sale__c/fields/Car_Name__c.field-meta.xml
<CustomField>
    <fullName>Car_Name__c</fullName>
    <label>Car Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Sale__c/fields/Car_Price__c.field-meta.xml
<CustomField>
    <fullName>Car_Price__c</fullName>
    <label>Car Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Archive_Sale__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <label>Seller Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <label>Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sold_Car__c/Sold_Car__c.object-meta.xml
<CustomObject>
    <label>Sold Car</label>
    <nameField>
        <label>Sold Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sold Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sold_Car__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <label>Seller</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Sold Cars</relationshipLabel>
    <relationshipName>Sold_Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sold_Car__c/fields/Sold_Car_Price__c.field-meta.xml
<CustomField>
    <fullName>Sold_Car_Price__c</fullName>
    <label>Sold Car Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ArchiveUtils.cls
public with sharing class ArchiveUtils {
    @AuraEnabled
    public static Boolean setToArchive() {
        try {
            List<Sold_Car__c> soldCars = [SELECT Name, Sold_Car_Price__c, Seller__r.Name, Seller__r.Id FROM Sold_Car__c];
            List<Archive_Sale__c> archives = new List<Archive_Sale__c>();

            Integer ind = 0;
            for(Sold_Car__c car : soldCars) {
                ind += 1;
                archives.add(
                    new Archive_Sale__c(
                        Name='Archive Number ' + ind,
                        Car_Name__c=car.Name,
                        Car_Price__c=car.Sold_Car_Price__c,
                        Seller_Name__c=car.Seller__r.Name
                    )
                );
            }

            insert archives;

            delete soldCars;

            return true;
        } catch(Exception e) {
            System.debug(e.getMessage());
            return false;
        }
    }
}