force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Seller_custom__c.field-meta.xml
<CustomField>
    <fullName>Seller_custom__c</fullName>
    <label>Seller_custom</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <label>Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CarInsertionMnpl.cls
public class CarInsertionMnpl {
    private List<Seller__c> sellers;

    public void manipulate(String type) {
        switch on type {
            when 'incrementCars' {
                SellerUpdageMnpl.incrementNumberOfCars(this.sellers);
            }
            when 'decrementCars' {
                SellerUpdageMnpl.decrementNumberOfCars(this.sellers);
            }
            when else {
                
            }
        }
    }

    public void fetchSellers(String sqlStatement) {
        this.sellers = Database.query(sqlStatement);
    }

    public List<ID> gatherSellerIds(List<Car__c> cars) {
        List<ID> sellerIds = new List<ID>();

        for(Car__c car : cars) {
            sellerIds.add(
                car.Seller_custom__c
            );
        }

        return sellerIds;
    }

}